from system import System
from bios import Bios
from ethernetcard import EthernetCard
from harddrive import HardDrive
from mainboard import Mainboard
from memorydimm import MemoryDimm
from processor import Processor
from soundcard import SoundCard
from videocard import VideoCard
